# project definitions
project: docs_xlabs_api
audience: developers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/docs/xlabs
topnav_title: xLabs Gaze API Documentation
homepage_title: xLabs Gaze API Documentation
site_title: xLabs Gaze API Documentation
project_folder: docs
company_name: xLabs
footer_image_location: ../../common_images/xLabs-logo-300x145.png
#github_editme_path: 
disqus_shortname: xlabsgaze-api-docs
# variables


sidebar_tagline: "API Docs"
sidebar_version: Version 0.1
theme_file: theme-blue.css
pdf_file_name: docs_xlabs_api_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'xlabs-api-documentation'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/

# same for all
host: 127.0.0.1
feedback_email: talk+docs@xlabs.com.au

# these settings should work, but they don't seem to apply the right highlighting

#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  auto_ids: true
#  hard_wrap: false
#  syntax_highlighter: rouge

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]


collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

