destination: ../doc_outputs/mydoc/xlabs-api-pdf
url: "http://127.0.0.1:4010"
baseurl: "/mydoc/xlabs-api--pdf"
port: 4010
output: pdf
print_title: xLabs API and Demo Documentation
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true